// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwcmneqipvnstzblpeui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Y21uZXFpcHZuc3R6YmxwZXVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk2ODg4MzUsImV4cCI6MjA4NTI2NDgzNX0.Oj_31X6LKpz8ntev0s2Lh9jmvCmciDi_mDIYh4klDAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});